import Head from 'next/head';

import Header from '@/Components/Header';
import styles from '@/styles/MainDoc.module.css';

import TitlePage from '../Components/TitlePage';

export default function About() {
    return <>
        <Head>
            <title>AppNext - About</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>


        <Header />
        <main className={styles.main} >
            <TitlePage title={'About us'} />

        </main>

    </>
}