import React, { useState } from 'react';

import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';

import Header from '@/Components/Header';
import style from '@/styles/Acount.module.css';
import stylesMain from '@/styles/MainDoc.module.css';

import TitlePage from '@/Components/TitlePage';
import { Router, useRouter } from 'next/router';

export default function Acount() {
    const router = useRouter()
    const [mail, setMail] = useState('')
    const [password, setPassword] = useState('')
    const handleMail = (e) => {
        setMail(e.target.value)
    }
    const handlePassword = (e) => {
        setPassword(e.target.value)
    }
    const handleSubmit = async (e) => {
        e.preventDefault();
        try {
            const response = await axios.post('/api/user/login', {
                mail, password
            })

            localStorage.setItem('app_user_token', response.data.token)


            router.push('/user/dashboard')
        } catch (error) {
            console.log('Loggedin failed !', error)
        }
    }
    return (
        <>
            <Head>
                <title>AppNext - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Header />
            <main className={stylesMain.main} >
                <TitlePage title={'Acount'} />
                <div className={style.form_container}>
                    <form onSubmit={handleSubmit} className={style.form} method="post">
                        <div className={style.form_row}>
                            <label htmlFor='mail'>Email : </label>
                            <input onChange={handleMail} value={mail} id='mail' type="email" />
                        </div>
                        <div className={style.form_row}>
                            <label htmlFor='pwd'>Password</label>
                            <input id='pwd' value={password} onChange={handlePassword} type="password" />
                        </div>
                        <div className={style.form_row}>

                            <input type="submit" value={'Login'} />
                        </div>
                    </form>
                    <div className={style.msg}>
                        You are not an account ?  <Link href="/acount">Register</Link>
                    </div>
                </div>
            </main>
        </>
    )

}
