import Header from "@/Components/Header";
import TitlePage from "@/Components/TitlePage";
import BlogCard from "./components/BlogCard";
import Head from "next/head";
import stylesMain from '@/styles/MainDoc.module.css';
import blogStyles from '@/styles/blogs/BlogStyle.module.css';

export default function Single(params) {

    return (
        <>
            <Head>
                <title>AppNext - Blogs Archives</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div

            >
                <Header />
                <main className={stylesMain.main}>
                    <TitlePage title={params ? params.title : 'Loading...'} />

                    <section className={blogStyles.section} >

                    </section>


                </main>
                <footer >

                </footer>
            </div>
        </>
    )

}
export async function getStaticProps({ params }) {
    const { slug } = params

    const res = await fetch(`/api/blogs/post?slug=${slug}`)
    // const res = await fetch(`http://localhost:3000/api/blogs/post`)
    const post = await res.json();


    return {
        props: {
            title: post[0].title,
            slug: post[0].slug,
            description: post[0].description
        }
    }
}
export async function getStaticPaths() {
    const res = await fetch('/api/blogs/archives')
    const posts = await res.json();
    const paths = posts.map((post) => ({ params: { slug: post.slug } })
    )
    return { paths, fallback: false }
}