import { useEffect, useState } from 'react';

import {
    Geist,
    Geist_Mono,
} from 'next/font/google';
import Head from 'next/head';

import Header from '@/Components/Header';
import TitlePage from '@/Components/TitlePage';
import styles from '@/styles/Home.module.css';
import stylesMain from '@/styles/MainDoc.module.css';
import blogStyles from '@/styles/blogs/BlogStyle.module.css'
import BlogCard from './components/BlogCard';



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export default function Home() {
    const [article, setArticle] = useState(null);

    useEffect(() => {
        const getArticles = async () => {
            const res = await fetch('/api/blogs/archives')
            const data = await res.json()
            setArticle(data)
        }
        if (!article) {
            getArticles();

        }


    }, [article])
    return (
        <>
            <Head>
                <title>AppNext - Blogs Archives</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
            >
                <Header />
                <main className={stylesMain.main}>
                    <TitlePage title={'Blog'} />

                    <section className={blogStyles.section} >
                        {
                            article ? article.map((el, id) => {
                                return <BlogCard key={id} article={el} />
                            })
                                : <p>Loading ...</p>
                        }
                    </section>


                </main>
                <footer className={styles.footer}>

                </footer>
            </div>
        </>
    );
}
